language: php
php:
- 7.1
env:
  matrix:
  - DB=MYSQL CORE_RELEASE=4
  global:
    secure: Le917O5p+3nccje9JNHyvFuQk44wkoXmfDYTV5tyfqH1yvTOS9aD2zUkSORbGBcxwFKbXxJxlhSH/TBub/ZjXoAlURw10oS8uzG5T4LVPkyKUNcph54Mbgs4E05K6IzOg78VlRZ6IOjBsXh/8NI51uEstgJZ/dajjPdERgjrd+k=
before_script:
- phpenv rehash
- git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
- php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
- cd ~/builds/ss
script:
- vendor/bin/phpunit vendor/colymba/silverstripe-restfulapi/tests/ --exclude-group CORSPreflight
